"""Docs/onboarding guard command hints for the ``easycat docs`` route map.

AUTO-GENERATED by scripts/regen_guard_commands.py from the repo justfile.
Do not edit by hand: change the ``guard-*`` recipe in the justfile, then
run ``uv run python scripts/regen_guard_commands.py``.
"""

# ruff: noqa: E501

from __future__ import annotations

DOCS_ONBOARDING_GUARD_COMMANDS: tuple[str, ...] = (
    "just guard-docs",
    "just guard-teaching",
    "just guard-examples",
    "just guard-contributing",
    "just guard-validation",
    "just guard-contracts",
    "just guard-ops",
)
