"""Contract tests for centralized lifecycle-budget defaults."""

from easycat.teardown_budgets import (
    AGENT_POST_DONE_STREAM_DRAIN_TIMEOUT_S,
    LLAMA_POST_CANCEL_AWAIT_TIMEOUT_S,
    REMOTE_RESPONSES_COMPLETED_STREAM_DRAIN_TIMEOUT_S,
    SESSION_APPLICATION_PROMPT_CANCEL_DRAIN_TIMEOUT_S,
    SESSION_AUDIO_DRAIN_TIMEOUT_S,
    SESSION_AUDIO_PLAYOUT_MARGIN_S,
    SESSION_BARGE_IN_CUTOFF_TIMEOUT_S,
    SESSION_FORCE_START_LOCK_TIMEOUT_S,
    SESSION_INLINE_SEND_CANCEL_GRACE_TIMEOUT_S,
    SESSION_INLINE_SEND_TIMEOUT_S,
    SESSION_SUPERSEDED_STOP_TIMEOUT_S,
)


def test_agent_lifecycle_budget_values_are_preserved() -> None:
    assert AGENT_POST_DONE_STREAM_DRAIN_TIMEOUT_S == 0.01
    assert LLAMA_POST_CANCEL_AWAIT_TIMEOUT_S == 2.0
    assert REMOTE_RESPONSES_COMPLETED_STREAM_DRAIN_TIMEOUT_S == 0.05


def test_session_lifecycle_budget_values_are_preserved() -> None:
    assert SESSION_AUDIO_DRAIN_TIMEOUT_S == 2.0
    assert SESSION_AUDIO_PLAYOUT_MARGIN_S == 0.5
    assert SESSION_INLINE_SEND_TIMEOUT_S == 0.5
    assert SESSION_INLINE_SEND_CANCEL_GRACE_TIMEOUT_S == 0.1
    assert SESSION_FORCE_START_LOCK_TIMEOUT_S == 0.5
    assert SESSION_SUPERSEDED_STOP_TIMEOUT_S == 0.5
    assert SESSION_BARGE_IN_CUTOFF_TIMEOUT_S == 0.4
    assert SESSION_APPLICATION_PROMPT_CANCEL_DRAIN_TIMEOUT_S == 0.1
